export const GET_COUNTRIES_REQUEST = 'GET_COUNTRIES_REQUEST';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_FAILURE = 'GET_COUNTRIES_FAILURE';

export const GET_COUNTRY_REQUEST = 'GET_COUNTRY_REQUEST';
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS';
export const GET_COUNTRY_FAILURE = 'GET_COUNTRY_FAILURE';

export const SET_COUNTRY_BY_NAME = 'SET_COUNTRY_BY_NAME';

export const FILTER_BY_REGION_REQUEST = 'FILTER_BY_REGION_REQUEST';
export const FILTER_BY_REGION_SUCCESS = 'FILTER_BY_REGION_SUCCESS';
export const FILTER_BY_REGION_FAILURE = 'FILTER_BY_REGION_FAILURE';